openapi: '3.0.2'
info:
  title: URL Shortener
  description: OpenApi Docs
  version: '1.0.0'
  license:
    name: MIT
    url: https://github.com/JorgeLNJunior/typescript-project/blob/master/LICENSE.md
servers:
  - url: http://localhost:3000
    description: local development server
paths:
  /{slug}:
    get:
      description: redirect to original URL
      summary: Redirect
      parameters:
        - name: slug
          in: path
          description: url slug
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not-found-error'
  /shorten:
    post:
      summary: Shorten a URL
      description: Shorten a URL and return his data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shorten-url-body'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/shorten-url-response'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad-request-error'
components:
  schemas:
    shorten-url-response:
      type: object
      properties:
        status:
          type: integer
          example: 201
        url:
          type: object
          properties:
            _id:
              type: string
              example: 60044d47768c227990ca7810
            original:
              type: string
              example: http://google.com
            short:
              type: string
              example: http://localhost:3000/r5174
            slug:
              type: string
              example: r5174
            createdAt:
              type: string
              example: 2021-01-17T14:44:23.301Z
            updatedAt:
              type: string
              example: 2021-01-17T14:44:23.301Z
    bad-request-error:
      type: object
      properties:
        status:
          type: number
          example: 400
        message:
          type: string
          example: bad request
        errors:
          type: array
          items:
            type: string
            example: url is required
    not-found-error:
      type: object
      properties:
        status:
          type: number
          default: 404
        message:
          type: string
          example: not found
        errors:
          type: array
          items:
            type: string
            example: url with slug "dS5Ve" was not found
    shorten-url-body:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          example: http://google.com
